command:
  print: False
  run: True

STIVI:
  Reconstruction_dir: /Users/abigot/SHOE/main/Reconstruction

DecodeWC:
  input: [
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0001.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0002.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0003.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0004.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0005.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0006.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0007.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0008.bin,
    /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1_Data_4_26_2025_Binary/Run_01_Config1_Data_4_26_2025_Binary_0009.bin
  ]
  use_stivi_merge: False  # use the embedded option in STIVI to merge files in same directory 
  output:
    name: /Users/abigot/CLINM/Calibration/CNAO_0425/Run_01_Config1.root  # auto or file name
    merge:
      activate: True
      rm_tmp_file: True  # remove temporary files
  exp: CLINM2025
  run: 1
  flat: True # True or False
  extra_option: "-rate -meas"